ProyectoSafe/WebSafe/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSafe.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoSafe/WebSafe/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DALC;
using System.Web.Security;

namespace WebSafe.Controllers
{
    public class MedicoController : Controller
    {
        // GET: Medico
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CalendarioMedico()
        {
            SafeEntities es = new SafeEntities();

            return View(es.VISITA_MEDICA.Where(a => a.ID_MEDICO == 1));
        }

        public ActionResult EstadoVisita(int id)
        {
            using (var se = new SafeEntities())
            {
                VISITA_MEDICA ev = se.VISITA_MEDICA.Find(id);
                return View(ev);
            }
        }

        [HttpPost]
        public ActionResult EstadoVisita(VISITA_MEDICA v)
        {
            try
            {
                using (var se = new SafeEntities())
                {
                    v.FECHA_CREACION = DateTime.Now;

                    VISITA_MEDICA vi = se.VISITA_MEDICA.Find(v.ID_VISITA);
                    vi.CONFIRMA = v.CONFIRMA;

 

                    se.SaveChanges();
                    return RedirectToAction("CalendarioMedico");
                }

            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

ProyectoSafe/WebSafe/Controllers/SupervisorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DALC;
using Negocio;
using System.Net.Mail;
using System.Net;
using WebSafe.Models;
using System.IO;
using Helpers;
using System.Web.UI.WebControls;
using System.Collections.Specialized;
using System.Configuration;

namespace WebSafe.Controllers
{
    public class SupervisorController : Controller
    {
        // GET: Supervisor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            SafeEntities es = new SafeEntities();
            return View(es.EVALUACION.ToList());
        }
        public ActionResult Editar(int id)
        {
            using (var se = new SafeEntities())
            {
                EVALUACION ev = se.EVALUACION.Find(id);
                return View(ev);
            }
        }

        [HttpPost]
        public ActionResult Editar(EVALUACION e)
        {
            try
            {
                using (var se = new SafeEntities())
                {
                    e.FECHA_CRECION = DateTime.Now;

                    EVALUACION ev = se.EVALUACION.Find(e.ID_EVALUACION);
                    ev.ID_TIPOEV = e.ID_TIPOEV;
                    ev.NOMBRE_EV = e.NOMBRE_EV;
                    ev.ID_TECNICO = e.ID_TECNICO;
                    ev.ID_EMPRESA = e.ID_EMPRESA;
                    ev.ENCARGADO_EV = e.ENCARGADO_EV;
                    ev.DESC_EV = e.DESC_EV;
                    ev.OBSERVACION = e.OBSERVACION;
                    ev.FECHA_CRECION = e.FECHA_CRECION;

                    se.SaveChanges();
                    return RedirectToAction("Listar");
                }

            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public ActionResult Eliminar(int id)
        {
            using (var se = new SafeEntities())
            {
                EVALUACION ev = se.EVALUACION.Find(id);
                se.EVALUACION.Remove(ev);
                se.SaveChanges();
                return RedirectToAction("Listar");
            }
        }



        /*--------------------------------------------------------------------------*/
        public ActionResult Visitas()
        {
            SafeEntities es = new SafeEntities();
            return View(es.VISITA_MEDICA.ToList());
        }

        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Crear(VISITA_MEDICA vi)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var context = new SafeEntities())
                {
                    vi.FECHA_CREACION = DateTime.Now;
                    vi.CONFIRMA = "P";

                    context.VISITA_MEDICA.Add(vi);
                    context.SaveChanges();
                    return RedirectToAction("Visitas");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al registrar Visita Medica" + ex.Message);
                return View();
            }
        }


        public ActionResult BorrarVisita(int id)
        {
            using (var se = new SafeEntities())
            {
                VISITA_MEDICA vi = se.VISITA_MEDICA.Find(id);
                se.VISITA_MEDICA.Remove(vi);
                se.SaveChanges();
                return RedirectToAction("Visitas");
            }
        }

        public ActionResult EditarVisita(int id)
        {
            using (var se = new SafeEntities())
            {
                VISITA_MEDICA vi = se.VISITA_MEDICA.Find(id);
                return View(vi);
            }
        }

        [HttpPost]
        public ActionResult EditarVisita(VISITA_MEDICA v)
        {
            try
            {
                using (var se = new SafeEntities())
                {
                    v.FECHA_CREACION = DateTime.Now;

                    VISITA_MEDICA vi = se.VISITA_MEDICA.Find(v.ID_VISITA);
                    vi.FECHA_VISITA = v.FECHA_VISITA;
                    vi.PACIENTE = v.PACIENTE;
                    vi.HORA_VISITA = v.HORA_VISITA;
                    vi.CONFIRMA = v.CONFIRMA;
                    vi.DESCRIPCION = v.DESCRIPCION;
                    vi.FECHA_CREACION = v.FECHA_CREACION;

                    se.SaveChanges();
                    return RedirectToAction("Visitas");
                }

            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public ActionResult ListaMedicos()
        {
            SafeEntities se = new SafeEntities();
            return View(se.MEDICO.ToList());
        }

        public ActionResult ObtenerMedico(int id)
        {    
           using (var se = new SafeEntities())
            {              
                MEDICO me = se.MEDICO.Find(id);
                if (me.ID_MEDICO == 1 || me.ID_MEDICO == 3)
                { 
                    
                }
                else if(me.ID_MEDICO == 2)
                {
                    
                }
                else
                {
                    
                }
            }
            return View("Visitas");
        }
       
        public ActionResult EnviarCorreo(int id)
        {

            using (var se = new SafeEntities())
            {
                VISITA_MEDICA vi = se.VISITA_MEDICA.Find(id);
                MailDefinition md = new MailDefinition();
                md.From = "notificaciones.safe@gmail.com";
                md.IsBodyHtml = true;
                md.Subject = "Tienes una Visita Medica!";
                md.BodyFileName = "~/ConfirmaHoraTemplate.html";

                ListDictionary replacements = new ListDictionary();
                replacements.Add("{nombre}", vi.MEDICO.NOMBRE_COMPLETO);
                replacements.Add("{paciente}", vi.PACIENTE);
                replacements.Add("{fecha}", vi.FECHA_VISITA);
                replacements.Add("{hora}", vi.HORA_VISITA);
                replacements.Add("{lugar}", vi.EMPRESA.RAZON_SOCIAL);
                replacements.Add("{direccion}", vi.EMPRESA.DIRECCION);


                //string body = "<div><p>Estimado(a) Medico(a) {nombre}, </p> <p>Le informamos que tiene una agendada una visita medica con el paciente {paciente} el dia {fecha} a las {hora}</p> <p> La visita debe realizarse en la empresa {lugar} cuya direccion es {direccion}</p> <p> saludos coordiales,</p> <p> Empresa Safe</p> </div>";

                MailMessage msg = md.CreateMailMessage(vi.MEDICO.EMAIL, replacements,new System.Web.UI.Control());
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 25;
                smtp.EnableSsl = true;
                String sCuentaCorreo = ("notificaciones.safe@gmail.com");
                String sPasswordCorreo = "safe12345";
                smtp.Credentials =
                    new System.Net.NetworkCredential(sCuentaCorreo, sPasswordCorreo);
                smtp.Send(msg);
                ViewBag.Send = "Mensaje enviado OK!!";
                return RedirectToAction("Visitas");
            }
            /*
            try
            {
                string nombre = vi.MEDICO.NOMBRE_COMPLETO;
                string paciente = vi.PACIENTE;
                string fecha = vi.FECHA_VISITA;
                string hora = vi.HORA_VISITA;
                string lugar = vi.EMPRESA.RAZON_SOCIAL;
                string direccion = vi.EMPRESA.DIRECCION;
                string mail = fillConfirmacionTemplate(nombre, paciente, fecha, hora, lugar, direccion);


                MailMessage correo = new MailMessage();
                correo.From = new MailAddress("notificaciones.safe@gmail.com");
                correo.To.Add(vi.MEDICO.EMAIL);
                correo.Subject = "Tienes una visita medica!";
                correo.SubjectEncoding = System.Text.Encoding.UTF8;
                correo.Body = mail;
                correo.IsBodyHtml = true;
                correo.Priority = MailPriority.Normal;
                //Path.GetTempPath() sustituye a Mappath
                //Path.GetTempPath()

                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 25;
                smtp.EnableSsl = true;
                String sCuentaCorreo = ("notificaciones.safe@gmail.com");
                String sPasswordCorreo = "safe12345";
                smtp.Credentials =
                    new System.Net.NetworkCredential(sCuentaCorreo, sPasswordCorreo);
                smtp.Send(correo);
                ViewBag.Send = "Mensaje enviado OK!!";              
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
            }
            return RedirectToAction("Visitas");
        }

        public static string fillConfirmacionTemplate(string nombre, string paciente, string fecha, string hora, string lugar, string direccion)
        {
            try
            {
                string directoryPath = Path.Combine(Directory.GetParent(AppDomain.CurrentDomain.BaseDirectory).Parent.FullName);
                string filePath = string.Format("{0}\\Helpers\\ConfirmaHoraTemplate.html", directoryPath);

                string filledTemplate = string.Empty;
                using (StreamReader reader = new StreamReader(filePath))
                {
                    filledTemplate = reader.ReadToEnd();
                }

                filledTemplate = filledTemplate.Replace("{nombre}", nombre);
                filledTemplate = filledTemplate.Replace("{paciente}", paciente);
                filledTemplate = filledTemplate.Replace("{fecha}", fecha);
                filledTemplate = filledTemplate.Replace("{hora}", hora);

ProyectoSafe/WebSafe/Controllers/TecnicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DALC;

namespace WebSafe.Controllers
{
    public class TecnicoController : Controller
    {
        // GET: Tecnico
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Formulario2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Formulario2(EVALUACION ev)
        {

            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var context = new SafeEntities())
                {
                    ev.FECHA_CRECION = DateTime.Now;

                    context.EVALUACION.Add(ev);
                    context.SaveChanges();
                    return RedirectToAction("Formulario2");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Eror al registrar Formulario" + ex.Message);
                return View();
            }

        }
        public ActionResult ListaTipoEvaluacion()
        {
            using (var se = new SafeEntities())
            {
                return PartialView(se.TIPO_EVALUACION.ToList());
            }
        }
    }
}

ProyectoSafe/WebSafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safe</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/justified-nav.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="container">
        <div class="masthead">
            <h3 class="text-muted">Portal Safe</h3>
            <ul class="nav nav-justified">
                <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                <li>@Html.ActionLink("Sobre Nosotros", "About", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
            </ul>
        </div>
        @RenderBody()

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
</body>
</html>
    

ProyectoSafe/WebSafe/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safe</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/justified-nav.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="container">
        <div class="masthead">
            <h3 class="text-muted">Portal Safe</h3>
            <ul class="nav nav-justified">
                <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                <li>@Html.ActionLink("Sobre Nosotros", "About", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
            </ul>
        </div>
        @RenderBody()

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
</body>
</html>

ProyectoSafe/WebSafe/Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Safe - Cliente</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:honeydew">
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div><center><img src="~/imagenes/Logo.png" width="20" height="20" /></center></div>
            </div>
            <div class="navbar-collapse navbar-static-top">
                <ul class="nav navbar-nav">
                    <li>
                        @{
                            if (Request.IsAuthenticated)
                            {
                                using (Html.BeginForm("Logout", "Inicio", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Cerrar Sesión</a>
                                }
                            }
                            else
                            {
                                @Html.ActionLink("Iniciar Sesión", "Login", "Account")
                            }
                        }
                    </li>
                    <li>@Html.ActionLink("Evaluaciones a Terreno", "EvaTerreno", "Cliente")</li>
                    <li>@Html.ActionLink("Capacitaciones", "Capacitaciones", "Cliente")</li>
                    <li>@Html.ActionLink("Visitas Medicas", "VisitasMed", "Cliente")</li>
                </ul>
            </div>
        </div>
    </div>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
        
    </ul>

    <div class="container-fluid body-content" style="background-color:honeydew">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year- Safe- Sistema de Gestión de Riesgos</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoSafe/WebSafe/Views/Shared/_LayoutLogin.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link href="~/Content/css/materialize.min.css" rel="stylesheet"
          type="text/css" media="screen,projection" />
    <link href="~/Content/css/custom.css" rel="stylesheet"
          type="text/css" />
</head>

<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/js/Jquery_Validate/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/js/materialize.js"></script>
    <script src="~/Content/js/custom.js"></script>

    <div class="site-content grey lighten-2">
        <div class="container custom grey lighten-5 z-depth-5">
            @RenderBody()
        </div>
    </div>

    </body>
</html>

ProyectoSafe/WebSafe/Views/Shared/_LayoutMedico.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safe</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/justified-nav.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/navbar.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Medico</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Cerrar Sesion", "Login", "Inicio")<span class="glyphicon glyphicon-user"></span></li>
                <li>@Html.ActionLink("Inicio", "Index", "Medico")<span class="glyphicon glyphicon-log-in"></span> </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="masthead">
            <h3 class="text-muted">Portal Safe</h3>
            <ul class="nav nav-justified">
                <li>@Html.ActionLink("Calendario", "CalendarioMedico", "Medico")</li>
            </ul>
        </div>
        @RenderBody()

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>


</body>
</html>

ProyectoSafe/WebSafe/Views/Shared/_LayoutSupervisor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safe</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/justified-nav.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/navbar.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Supervisor</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Cerrar Sesion", "Login", "Inicio")<span class="glyphicon glyphicon-user"></span></li>
                <li>@Html.ActionLink("Inicio", "Index", "Supervisor")<span class="glyphicon glyphicon-log-in"></span> </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="masthead">
            <h3 class="text-muted">Portal Safe</h3>
            <ul class="nav nav-justified">
                <li>@Html.ActionLink("Evaluaciones", "Listar", "Supervisor")</li>
                <li>@Html.ActionLink("Visitas Medicas", "Visitas", "Supervisor")</li>
                <li>@Html.ActionLink("Capacitaciones", "ListaCap", "Supervisor")</li>
            </ul>
        </div>
        @RenderBody()

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>


</body>
</html>

ProyectoSafe/WebSafe/Views/Shared/_LayoutTecnico.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safe</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/justified-nav.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/navbar.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Trabajador</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><text>Hola @User.Identity.Name !</text><span class="glyphicon glyphicon-user"></span></li>
                <li>@Html.ActionLink("Cerrar Sesion", "Login", "Inicio")<span class="glyphicon glyphicon-user"></span></li>
                <li>@Html.ActionLink("Inicio", "Index", "Tecnico")<span class="glyphicon glyphicon-log-in"></span> </li>
            </ul>
        </div>
    </nav>

    @RenderBody()

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>


</body>
</html>