ProyectoSafe/WebSafe/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio.Vistas;
using DALC;

namespace WebSafe.Controllers
{
    public class AdministradorController : Controller
    {
        // GET: Administrador

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult MantenedorEmpresas()
        {
            SafeEntities se = new SafeEntities();

            return View(se.EMPRESA.ToList());
        }

        public ActionResult AgregarEmpresa()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarEmpresa(EMPRESA e)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var se = new SafeEntities())
                {
                    se.EMPRESA.Add(e);
                    se.SaveChanges();
                    return RedirectToAction("MantenedorEmpresas");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al registrar Empresa " + ex.Message);
                return View();
            }
        }

        public ActionResult ListaTipoEmpresa()
        {
            using (var se = new SafeEntities())
            {
                return PartialView(se.TIPO_EMPRESA.ToList());
            }
        }
        public ActionResult EditarEmpresa(int id)
        {
            using (var se = new SafeEntities())
            {
                EMPRESA emp = se.EMPRESA.Find(id);
                return View(emp);
            }
                
        }

        [HttpPost]
        public ActionResult EditarEmpresa(EMPRESA e)
        {
            try
            {
                using (var se = new SafeEntities())
                {
                    EMPRESA emp = se.EMPRESA.Find(e.ID_EMPRESA);
                    emp.ID_TIPOEMPRESA = e.ID_TIPOEMPRESA;
                    emp.RAZON_SOCIAL = e.RAZON_SOCIAL;
                    emp.RUT_EMPRESA = e.RUT_EMPRESA;
                    emp.REPRESENTANTE_LEGAL = e.REPRESENTANTE_LEGAL;
                    emp.DIRECCION = e.DIRECCION;
                    emp.EMAIL = e.EMAIL;
                    emp.TELEFONO = e.TELEFONO;
                    emp.PAGINA_WEB = e.PAGINA_WEB;

                    se.SaveChanges();

                    return RedirectToAction("MantenedorEmpresas");
                }
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        public ActionResult DetallesEmpresa(int id)
        {
            using (var se = new SafeEntities())
            {
                EMPRESA emp = se.EMPRESA.Find(id);
                return View(emp);

            }
        }

        public ActionResult EliminarEmpresa(int id)
        {
            using (var se = new SafeEntities())
            {
                EMPRESA emp = se.EMPRESA.Find(id);
                se.EMPRESA.Remove(emp);
                se.SaveChanges();
                return RedirectToAction("MantenedorEmpresas");
            }
        }

        public ActionResult MantenedorEvaluacion()
        {
            SafeEntities se = new SafeEntities();

            return View(se.EVALUACION.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarEvaluacion(EVALUACION ev)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var se = new SafeEntities())
                {
                    se.EVALUACION.Add(ev);
                    se.SaveChanges();
                    return RedirectToAction("MantenedorEvaluacion");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al registrar Evaluacion" + ex.Message);
                return View();
            }
        }

        public ActionResult EditarEvaluacion()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarEvaluacion(EVALUACION ev)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                DateTime fechacreacion = DateTime.Now;
                using (var se = new SafeEntities())
                {
                    EVALUACION eva = se.EVALUACION.Find(ev.ID_EVALUACION);
                    eva.ID_TIPOEV = ev.ID_TIPOEV;
                    eva.NOMBRE_EV = ev.NOMBRE_EV;
                    eva.ID_TECNICO = ev.ID_TECNICO;
                    eva.ID_EMPRESA = ev.ID_EMPRESA;
                    eva.ENCARGADO_EV = ev.ENCARGADO_EV;
                    eva.DESC_EV = ev.DESC_EV;
                    eva.OBSERVACION = ev.OBSERVACION;
                    eva.FECHA_CRECION = fechacreacion;

                    se.SaveChanges();

                    return RedirectToAction("MantenedorEmpresa");
                }
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        public ActionResult DetallesEvaluacion(decimal ID_EVALUACION)
        {
            using (var se = new SafeEntities())
            {
                EVALUACION eva = se.EVALUACION.Find(ID_EVALUACION);
                return View(eva);

            }
        }

        public ActionResult MantenedorUsuario()
        {
            SafeEntities se = new SafeEntities();
            return View(se.USUARIO.ToList());
        }

        public ActionResult AgregarUsuario()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarUsuario(USUARIO u)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var se = new SafeEntities())
                {
                    se.USUARIO.Add(u);
                    se.SaveChanges();
                    return RedirectToAction("MantenedorEmpresas");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al registrar Usuario " + ex.Message);
                return View();
            }
        }

        public ActionResult ListaTipoUsuario()
        {
            using (var se = new SafeEntities())
            {
                return PartialView(se.TIPO_USUARIO.ToList());
            }
        }


        public ActionResult EditarUsuario(int id)
        {
            using (var se = new SafeEntities())
            {
                USUARIO usu = se.USUARIO.Find(id);
                return View();
            }

        }

        [HttpPost]
        public ActionResult EditarUsuario(USUARIO u)
        {
            try
            {
                
                using (var se = new SafeEntities())
                {
                    u.FECHA_CREACION = DateTime.Now;
                    USUARIO usu = se.USUARIO.Find(u.ID_USUARIO);
                    usu.USERNAME = u.USERNAME;
                    usu.PASS = u.PASS;
                    usu.RUT_USUARIO = u.RUT_USUARIO;
                    usu.NOMBRE = u.NOMBRE;
                    usu.APELLIDO_PATERNO = u.APELLIDO_PATERNO;
                    usu.APELLIDO_MATERNO = u.APELLIDO_MATERNO;
                    usu.FECHA_NACIMIENTO = u.FECHA_NACIMIENTO;
                    usu.EMAIL = u.EMAIL;
                    usu.TELEFONO = u.TELEFONO;
                    usu.FECHA_CREACION = u.FECHA_CREACION;
                    usu.ID_EMPRESA = u.ID_EMPRESA;
                    usu.ID_TIPOUS = u.ID_TIPOUS;

 
                    se.SaveChanges();

                    return RedirectToAction("MantenedorEmpresas");
                }
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        public ActionResult DetallesUsuario(int id)
        {
            using (var se = new SafeEntities())
            {
                USUARIO emp = se.USUARIO.Find(id);
                return View(emp);

            }
        }

        public ActionResult EliminarUsuario(int id)
        {
            using (var se = new SafeEntities())
            {
                USUARIO usu = se.USUARIO.Find(id);
                se.USUARIO.Remove(usu);
                se.SaveChanges();
                return RedirectToAction("MantenedorEmpresas");
            }
        }
    }
}

ProyectoSafe/WebSafe/Views/Administrador/AgregarEmpresa.cshtml
@model DALC.EMPRESA

@{
    ViewBag.Title = "AgregarEmpresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgregarEmpresa</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPRESA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_TIPOEMPRESA, "ID_TIPOEMPRESA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("ListaTipoEmpresa", "Administrador")
                @Html.ValidationMessageFor(model => model.ID_TIPOEMPRESA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAZON_SOCIAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAZON_SOCIAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RAZON_SOCIAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RUT_EMPRESA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUT_EMPRESA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUT_EMPRESA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.REPRESENTANTE_LEGAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REPRESENTANTE_LEGAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REPRESENTANTE_LEGAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIRECCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIRECCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIRECCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TELEFONO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TELEFONO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAGINA_WEB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAGINA_WEB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAGINA_WEB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "MantenedorEmpresas")
</div>

ProyectoSafe/WebSafe/Views/Administrador/AgregarEvaluacion.cshtml
@model DALC.EVALUACION

@{
    ViewBag.Title = "AgregarEvaluacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Evaluacion</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EVALUACION</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_EVALUACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_EVALUACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_EVALUACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_TIPOEV, "ID_TIPOEV", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_TIPOEV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_TIPOEV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE_EV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE_EV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE_EV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TECNICO_EV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TECNICO_EV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TECNICO_EV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPRESA_EV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPRESA_EV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPRESA_EV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENCARGADO_EV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ENCARGADO_EV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENCARGADO_EV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESC_EV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESC_EV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESC_EV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OBSERVACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OBSERVACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OBSERVACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_CRECION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_CRECION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_CRECION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoSafe/WebSafe/Views/Administrador/AgregarUsuario.cshtml
@model DALC.USUARIO

@{
    ViewBag.Title = "AgregarUsuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgregarUsuario</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USUARIO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_USUARIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_USUARIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RUT_USUARIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUT_USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUT_USUARIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APELLIDO_PATERNO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APELLIDO_PATERNO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APELLIDO_PATERNO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APELLIDO_MATERNO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APELLIDO_MATERNO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APELLIDO_MATERNO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_NACIMIENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_NACIMIENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_NACIMIENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TELEFONO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TELEFONO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_CREACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_CREACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_CREACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_EMPRESA, "ID_EMPRESA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_EMPRESA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_EMPRESA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_TIPOUS, "ID_TIPOUS", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_TIPOUS", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_TIPOUS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoSafe/WebSafe/Views/Administrador/EditarEmpresa.cshtml
@model DALC.EMPRESA

@{
    ViewBag.Title = "EditarEmpresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditarEmpresa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPRESA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_EMPRESA)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_TIPOEMPRESA, "ID_TIPOEMPRESA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("ListaTipoEmpresa", "Administrador")
                @Html.ValidationMessageFor(model => model.ID_TIPOEMPRESA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAZON_SOCIAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RAZON_SOCIAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RAZON_SOCIAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RUT_EMPRESA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUT_EMPRESA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUT_EMPRESA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.REPRESENTANTE_LEGAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REPRESENTANTE_LEGAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REPRESENTANTE_LEGAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIRECCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIRECCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIRECCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TELEFONO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TELEFONO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAGINA_WEB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAGINA_WEB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAGINA_WEB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MantenedorEmpresas")
</div>

ProyectoSafe/WebSafe/Views/Administrador/ListaTipoEmpresa.cshtml
@model IEnumerable<DALC.TIPO_EMPRESA>

<select class="form-control" id="ID_TIPOEMPRESA" name="ID_TIPOEMPRESA">

@foreach (var item in Model) {
   <option value="@item.ID_TIPOEMPRESA">@item.RUBRO</option>
}

</select>